apiVersion: ako.vmware.com/v1alpha1
kind: AviInfraSetting
metadata:
  name: my-infrasetting
spec:
  seGroup:
    name: L7-SEGroup
  network:
    vipNetworks:
      - networkName: Workload1-VDS-PG
        cidr: 192.168.12.0/24
    nodeNetworks:
      - networkName: Workload0-VDS-PG
        cidrs:
        - 192.168.11.0/24
    enableRhi: false
    bgpPeerLabels: []
    #bgpPeerLabels:
      #- peer1
      #- peer2
  l7Settings:
    shardSize: SMALL
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: avi-gateway-class
spec:
  controller: ako.vmware.com/avi-lb
  parametersRef:
    group: ako.vmware.com
    kind: AviInfraSetting
    name: my-infrasetting