namespace: tanzu-system-service-discovery

deployment:
  args:
    - --source=service
    - --source=ingress
    - --source=contour-httpproxy
    - --domain-filter=k8s.lab.test
    - --policy=upsert-only
    - --registry=txt
    - --txt-owner-id=k8s
    - --txt-prefix=external-dns-
    - --provider=rfc2136
    - --rfc2136-host=192.168.100.1
    - --rfc2136-port=53
    - --rfc2136-zone=k8s.lab.test
    - --rfc2136-tsig-secret=JuXFt6ORFjAzHAHl48PnGPeLwukPfArS/Vzj+H2k/UA=
    - --rfc2136-tsig-secret-alg=hmac-sha256
    - --rfc2136-tsig-keyname=externaldns-key
    - --rfc2136-tsig-axfr