apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
         "type": "static",
         "addresses": [
           {
             "address": "192.168.103.200/23",
             "gateway": "192.168.102.1"
           }
         ],
         "routes": [
           { "dst": "192.168.100.0/23", "gw": "192.168.102.1" }
         ]
      }
  }'
